services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3000:3000
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./frontend:/app